### ISSUE TITLE
No resource or method named `shell_out' for `Chef::Recipe "package"'

### ISSUE THREAD

**Issue by cleveranecdote** [chef-cookbooks/memcached#49]
Running client 11.14.6 and get this error with 1.8.0. chef-docker had similar issue and was fixed with
include Chef::Mixin::ShellOut
https://github.com/bflad/chef-docker/issues/353

version 1.7.2 is successful

Output:

[2015-09-03T21:57:11+00:00] WARN: Current  service[collectd]: /var/chef/cache/cookbooks/collectd/recipes/default.rb:138:in `from_file'

  ================================================================================
  Recipe Compile Error in /var/chef/cache/cookbooks/memcached/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  No resource or method named `shell_out' for `Chef::Recipe "package"'

  Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/memcached/recipes/package.rb:23:in `from_file'
    /var/chef/cache/cookbooks/memcached/recipes/default.rb:20:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/memcached/recipes/package.rb:

   16:  # See the License for the specific language governing permissions and
   17:  # limitations under the License.
   18:  #
   19:
   20:  # include epel on redhat/centos 5 and below in order to get the memcached packages
   21:  include_recipe 'yum-epel' if node['platform_family'] == 'rhel' && node['platform_version'].to_i == 5
   22:
   23>> if node['platform_family'] == 'debian' && shell_out('dpkg -l memcached | grep "^ii  memcached"').error?
   24:    # dpkg, imma let you finish but don't start services automatically
   25:    # https://jpetazzo.github.io/2013/10/06/policy-rc-d-do-not-start-services-automatically/
   26:    execute 'disable auto-start' do
   27:      command 'echo exit 101 > /usr/sbin/policy-rc.d ; chmod +x /usr/sbin/policy-rc.d'
   28:    end
   29:
   30:    package 'memcached' do
   31:      version node['memcached']['version']
   32:      action :install

**Comment by tas50** [comment]
I've removed the use of shell_out, which should resolve your issues
