### ISSUE TITLE
Centos 6 init.d script is not correct

### ISSUE THREAD

**Issue by koertkuipers** [chef-cookbooks/memcached#76]
### Cookbook version

Release 3.0.2
### Chef-client version

chef-12.11.18-1.el6.x86_64.rpm
### Platform Details

CentOS release 6.7 (Final)
### Scenario:

run the recipe memcached::default
### Steps to Reproduce:

$ kitchen converge default-centos-67
### Expected Result:

memcached launches without errors
### Actual Result:

```
[vagrant@default-centos-67 ~]$ sudo /sbin/service memcached start
Starting memcached: chown: missing operand after `/var/run/memcached'
Try `chown --help' for more information.
```

the issue seems to be that the variable user in template is not defined?
the init.d script as a result has this invalid line:
`chown  /var/run/memcached`
 which is based on this line from template:
`chown <%= @user %> /var/run/memcached`

**Comment by buererra** [comment]
+1

**Comment by tas50** [comment]
I need to fix the init scripts in general. It's on the to-do list

**Comment by tas50** [comment]
My testing of the RHEL init scripts are passing now so I'm going to close this one out. I *believe* we have it all fixed
